# Generated by Django 3.2.4 on 2021-06-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=150, verbose_name='Марка')),
                ('color', models.CharField(max_length=150, verbose_name='Цвет')),
                ('enginvol', models.IntegerField(verbose_name='Объем двигателя')),
                ('transmission', models.CharField(max_length=150, verbose_name='Коробка передач')),
                ('oil', models.CharField(max_length=150, verbose_name='Вид топлива')),
            ],
        ),
    ]
