# Generated by Django 3.2.4 on 2021-06-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Renthouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('flour', models.CharField(max_length=150, verbose_name='Этаж')),
                ('numroom', models.IntegerField(verbose_name='Кол-во комнат')),
                ('numdays', models.IntegerField(verbose_name='Кол-во дней')),
                ('cost', models.CharField(max_length=150, verbose_name='Стоимость')),
            ],
        ),
    ]
