# Generated by Django 3.2.4 on 2021-06-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renthouse',
            name='cost',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='renthouse',
            name='flour',
            field=models.IntegerField(verbose_name='Этаж'),
        ),
    ]
